version: '3.8'

services:
  web:
    # Bouw de container op basis van het Dockerfile in deze map
    build: .
    container_name: apache-php
    ports:
      - "80:80"
    volumes:
      # Koppel je lokale html-map aan de container
      - ./html:/var/www/html
    depends_on:
      - db
    
  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: my_database
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_password
    volumes:
      - ./db_data:/var/lib/mysql
  
  phpmyadmin:
    # Gebruik de officiële phpMyAdmin-image
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      # Koppel phpMyAdmin aan je MySQL-container
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysecretpassword
    depends_on:
      - db